version: 2.1

executors:
  android-executor:
    docker:
      - image: circleci/android:api-30
    # environment:
    #   JAVA_HOME: /usr/lib/jvm/java-17-openjdk
    #   PATH: /usr/lib/jvm/java-17-openjdk/bin:$PATH
    working_directory: ~/frontend

jobs:
  build:
    executor: android-executor
    steps:
      - checkout

      - run:
          name: Install OpenJDK 17
          command: |
            sudo apt-get update && sudo apt-get install openjdk-17-jdk
            sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
            sudo update-alternatives --set javac /usr/lib/jvm/java-17-openjdk-amd64/bin/javac
            java -version

      # # Install Java 17
      # - run:
      #     name: Install Java 17
      #     command: |
      #       sudo apt update
      #       sudo apt install -y openjdk-17-jdk
      # - run:
      #     name: Verify Java version
      #     command: java -version

      # Restore Gradle cache
      - restore_cache:
          keys:
            - gradle-cache-{{ checksum "frontend/gradle/wrapper/gradle-wrapper.properties" }}
            - gradle-cache-

      # Download and set up dependencies
      - run:
          name: Install dependencies
          command: cd frontend && ./gradlew dependencies

      # Save Gradle cache
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-cache-{{ checksum "frontend/gradle/wrapper/gradle-wrapper.properties" }}

      # Run the build to check if it compiles
      - run:
          name: Build APK
          command: cd frontend && ./gradlew assembleDebug

      # Store the APK as an artifact (optional)
      - store_artifacts:
          path: frontend/app/build/outputs/apk/debug
          destination: apk

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
